# Generated by Django 5.2 on 2025-05-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_encryptedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='original_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
