# Generated by Django 5.2 on 2025-06-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_accesslog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslog',
            name='file',
        ),
        migrations.AddField(
            model_name='accesslog',
            name='file_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
